# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]

[backend.basic_station]
region="IN865"
frequency_min=865000000
frequency_max=867000000

[backend.semtech_udp]
fake_rx_time=true